// src/components/RowProduto.vue
<template>
  <RouterLink
    :to="`/produto/${produto.id}`"
    class="flex items-center gap-3"
    :class="classes"
  >
    <img
      loading="lazy"
      :src="`./img/produtos/${produto.id}.png`"
      alt="Imagem do produto"
      class="block object-contain aspect-square border border-secondary rounded-sm"
      :class="img"
    />
    <div>
      <h2
        v-html="deixaNomeDoProdutoIgualPesquisaNegrito"
        class="break-all text-secondary font-semibold"
      ></h2>
      <p
        v-html="deixaCodigoDoProdutoIgualPesquisaNegrito"
        class="text-gray-600"
        :class="codigos"
      ></p>
    </div>
  </RouterLink>
</template>

<script lang="ts">
import type { IProduto } from "@/interface/IProdutos";
import type { PropType } from "vue";

export default {
  data() {
    return {
      compressor: false,
    };
  },
  props: {
    produto: {
      type: Object as PropType<IProduto>,
      required: true,
    },
    classes: {
      type: String,
    },
    img: {
      type: String,
    },
    codigos: {
      type: String,
    },
    negrito: {
      type: String,
    },
  },
  computed: {
    deixaNomeDoProdutoIgualPesquisaNegrito() {
      let nome = this.produto.nome;
      if (!this.negrito) return nome;

      const termos = this.negrito.split(" ").filter(Boolean);
      termos.forEach((termo) => {
        const regex = new RegExp(`(${termo})`, "gi");
        nome = nome.replace(regex, `<span class="font-bold">$1</span>`);
      });

      return nome;
    },

    deixaCodigoDoProdutoIgualPesquisaNegrito() {
      let codigo = this.produto.codigos.join(", ");
      if (!this.negrito) return codigo;

      const termos = this.negrito.split(" ").filter(Boolean);
      termos.forEach((termo) => {
        const regex = new RegExp(`(${termo})`, "gi");
        codigo = codigo.replace(regex, `<span class="font-bold">$1</span>`);
      });

      return codigo;
    },
  },
};
</script>

// src/components/RowProduto/index.tsx
import { IProdutos } from '@/interface/IProdutos';
import ExportedImage from 'next-image-export-optimizer';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import slugify from 'slugify';

interface Props {
  produto: IProdutos;
  imgSize: string;
  pesquisa?: string;
}

const RowProduto = ({ produto, imgSize, pesquisa = '' }: Props) => {
  function deixaNomeDoProdutoIgualPesquisaNegrito() {
    let nome = produto.nome;
    if (!pesquisa) return nome;

    const termos = pesquisa.split(' ').filter(Boolean);
    termos.forEach((termo) => {
      const regex = new RegExp(`(${termo})`, 'gi');
      nome = nome.replace(regex, `<span class="font-bold">$1</span>`);
    });

    return nome;
  }

  function deixaCodigoDoProdutoIgualPesquisaNegrito() {
    let codigo = produto.codigos.join(', ');
    if (!pesquisa) return codigo;

    const termos = pesquisa.split(' ').filter(Boolean);
    termos.forEach((termo) => {
      const regex = new RegExp(`(${termo})`, 'gi');
      codigo = codigo.replace(regex, `<span class="font-bold">$1</span>`);
    });

    return codigo;
  }

  const path = process.env.NEXT_PUBLIC_WEBSITE_BASE_PATH;

  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);
  if (!mounted) return null;

  return (
    <Link
      href={`/produto/${slugify(produto.sku, { lower: true, strict: true })}`}
      className="flex items-center gap-3"
    >
      <ExportedImage
        width={60}
        height={60}
        placeholder="empty"
        src={`${path}/assets/img/produtos/${produto.id}.png`}
        alt=""
        className={`block object-contain aspect-square border border-secondary rounded-sm ${imgSize}`}
      />
      <div>
        <h2
          dangerouslySetInnerHTML={{
            __html: deixaNomeDoProdutoIgualPesquisaNegrito(),
          }}
          className="break-all text-secondary font-semibold"
        />
        <p
          dangerouslySetInnerHTML={{
            __html: deixaCodigoDoProdutoIgualPesquisaNegrito(),
          }}
          className="text-gray-600"
        />
      </div>
    </Link>
  );
};

export default RowProduto;
