// src/components/DisplayProduto.vue
<template>
  <div class="absolute py-4 pb-0 shadow-md w-full bg-base-100 top-16">
    <p class="text-gray-600 px-4 pb-4">
      Resultado da pesquisa para: {{ produtoPesquisado }}
    </p>
    <div class="max-h-[70vh] overflow-auto" v-if="produtos.length">
      <RowProduto
        v-for="(produto, index) in produtos"
        :key="index"
        class="hover:bg-base-200 p-5 border-t border-gray-300"
        :produto="produto"
        @click="limpaPesquisa"
      />
    </div>
    <p class="pb-5 px-5 italic" v-else>Nenhum resultado encontrado.</p>
  </div>
</template>

<script lang="ts">
import type { IProduto } from "@/interface/IProdutos";
import { storeProdutos } from "@/store/SProdutos";
import RowProduto from "./RowProduto.vue";

export default {
  components: { RowProduto },
  props: {
    produtoPesquisado: { type: String, required: true },
  },
  data() {
    return {
      SProdutos: storeProdutos(),
      produtos: [] as IProduto[],
    };
  },
  methods: {
    async pesquisaProdutos() {
      if (this.produtoPesquisado.length > 0) {
        this.produtos = await (
          await this.SProdutos
        ).pesquisaProduto(this.produtoPesquisado);
      } else {
        this.produtos = [];
      }
    },
    limpaPesquisa() {
      this.$emit("limpaPesquisa");
    },
  },
  watch: {
    produtoPesquisado: {
      immediate: true,
      handler: "pesquisaProdutos",
    },
  },
  emits: ["limpaPesquisa"],
};
</script>

// src/components/InputPesquisa/DisplayProduto/index.tsx
'use client';

import styles from './DisplayProduto.module.css';
import RowProduto from '@/components/RowProduto';
import { IProdutos } from '@/interface/IProdutos';
import getProdutos from '@/utils/getProdutos';

interface Props {
  pesquisa: string;
}

const DisplayProduto = ({ pesquisa }: Props) => {
  const produtos: IProdutos[] = getProdutos.todos();

  const filtrarProdutos = () => {
    if (pesquisa.trim() === '') return [];
    const tokens = pesquisa.trim().toLowerCase().split(/\s+/).filter(Boolean);

    return produtos.filter((p) => {
      const sku = p.sku.toLowerCase();
      const nome = p.nome.toLowerCase();
      const id = p.id.toLowerCase();
      const combinado = `${sku} ${nome} ${id}`;
      return tokens.every((t) => combinado.includes(t));
    });
  };

  const produtosFiltrados = filtrarProdutos();

  return (
    <div
      className={`${styles.contanerDisplayProduto} absolute block z-50 rounded-md shadow-md w-full bg-base-100 top-16`}
    >
      {/* <!-- <p className="text-gray-600 px-4 pb-4">
      Resultado da pesquisa para: {{ produtoPesquisado }}
    </p> --> */}
      {produtosFiltrados.length > 0 ? (
        <div className="max-h-[45vh] mr-1 rounded-md overflow-auto">
          {produtosFiltrados?.map((produto, index) => (
            <div
              key={`${produto.id}-${index}`}
              className="hover:bg-base-200 p-1.5 border-b border-gray-300"
            >
              <RowProduto
                produto={produto}
                imgSize="h-10"
                pesquisa={pesquisa}
              />
            </div>
          ))}
        </div>
      ) : (
        <p className="py-5 px-5 italic">Nenhum resultado encontrado.</p>
      )}
    </div>
  );
};

export default DisplayProduto;
