// src/components/SetaLink.vue
<template>
  <div class="breadcrumbs pb-0 text-sm">
    <ul>
      <li>
        <RouterLink class="" to="/">Pagina inicial</RouterLink>
      </li>
      <li class="">
        <p class="break-all w-fit">{{ id }}</p>
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
export default {
  props: {
    id: {
      type: String,
      required: true,
    },
  },
};
</script>

// src/components/SetaLink/index.tsx
import Link from 'next/link';

const SetaLink = ({ nome }: { nome: string }) => {
  return (
    <div className="breadcrumbs pb-0 text-sm">
      <ul>
        <li>
          <Link className="" href="/">
            Pagina inicial
          </Link>
        </li>
        <li className="">
          <p className="break-all w-fit">{nome}</p>
        </li>
      </ul>
    </div>
  );
};

export default SetaLink;
